---
title: "ガンマ分布"
author: "Ryo Nakagami"
date: "2024-10-05"
date-modified: last-modified
number_sections: false
code-fold: true
comments:
    utterances:
         repo: RyoNakagami/statistics-for-regression-monkey
         label: discussion
---

## ガンマ分布の性質

<div class="blog-custom-border">
<strong>Def: ガンマ分布</strong> <br>

確率変数 $\operatorname{X}$ がガンマ分布に従うとき，その確率密度関数は


$$
\begin{align*}
\operatorname{Gam}(x; a, b) &= \frac{1}{b^a\Gamma(a)} x^{a-1} \exp[-x/b], \quad x > 0\\
\text{where}\quad & a >0, b > 0
\end{align*}
$$

このとき，$X$ はパラメータ $(a, b)$ のガンマ分布に従うという．

- $a$: 形状パラメーター(shape parameter)
- $b$: 尺度パラメーター(scale parameter)

</div>

```{python}
from regmonkey_style import stylewizard as sw
from scipy.stats import gamma
import plotly.graph_objs as go
import numpy as np

sw.set_templates('regmonkey_line')
N = 1000
x = np.linspace(0, 6, N)[1:]
a= [0.5, 2, 5]
scale = 1
y_values =list( map(lambda shape: gamma(a=shape, scale=1).pdf(x), a))

# Create traces for each shape parameter
traces = []
for i, shape in enumerate(a):
    traces.append(go.Scatter(
        x=x,
        y=list(y_values)[i],
        mode='lines',
        name=f'Gamma(a={shape})'
    ))
# Create figure and add traces
fig = go.Figure(data=traces)
fig.update_layout(
    yaxis=dict(
        range=[0, 0.8],
        fixedrange = True
    ),
    xaxis=dict(
        range=[0, 5],
        fixedrange = True
    ),
    title="Gamma Distribution PDF for Different Shape Parameters",
    xaxis_title="x",
    yaxis_title="PDF"
)
# Show the plot
fig.show()
```

<strong > &#9654;&nbsp; 確率密度関数の積分値が１になる確認</strong>

$z = x/b$ という変数変換を用いることで以下のように示すことができます．

$$
\begin{align*}
\int_0^\infty f(x) \mathrm{d}x
    &= \int_0^\infty\frac{1}{b^a\Gamma(a)} x^{a-1} \exp[-x/b]\mathrm{d}x\\
    &= \int_0^\infty\frac{1}{b\Gamma(a)} z^{a-1} \exp[-z]b\mathrm{d}z\\
    &= \frac{1}{\Gamma(a)}\underbrace{\int_0^\infty z^{a-1} \exp[-z]\mathrm{d}z}_{=\Gamma(a)}\\
    &=1
\end{align*}
$$


<strong > &#9654;&nbsp; 期待値の導出</strong>

$$
\begin{align*}
\mathbb E[X]
    &= \int_0^\infty x \frac{1}{b^a\Gamma(a)} x^{a-1} \exp[-x/b] \mathrm{d}x\\
    &= ab\int_0^\infty \underbrace{\frac{1}{b^{a+1}\Gamma(a+1)} x^{(a+1)-} \exp[-x/b]}_{\operatorname{Gam}(a+1, b)\text{の密度関数}} \mathrm{d}x\\
    &=ab
\end{align*}
$$

$$\tag*{\(\blacksquare\)}$$

または，$z = x/b$ という変数変換を用いて以下のようにも示せます．

$$
\begin{align*}
\mathbb E[X]
    &= \int_0^\infty x \frac{1}{b^a\Gamma(a)} x^{a-1} \exp[-x/b] \mathrm{d}x\\
    &= \int_0^\infty \frac{1}{b^a\Gamma(a)} x^{a} \exp[-x/b] \mathrm{d}x\\
    &= \int_0^\infty \frac{1}{b^{a+1}\Gamma(a)} (bz)^a \exp[-z] \mathrm{d}z\\
    &= \frac{1}{b\Gamma(a)}\underbrace{\int_0^\infty z^{(a+1)-1} \exp[-z] \mathrm{d}z}_{=\Gamma(a+1)}\\
    &= \frac{a\Gamma(a)}{b\Gamma(a)} \quad\because \Gamma(a+1) = a\Gamma(a)\\
    &= ab
\end{align*}
$$

<strong > &#9654;&nbsp; 分散の導出</strong>

$$
\begin{align*}
\mathbb E[X^2]
    &= \int_0^\infty x^2 \frac{1}{b^a\Gamma(a)} x^{a-1} \exp[-x/b] \mathrm{d}x\\
    &= a(a+1)b^2 \int_0^\infty \underbrace{\frac{1}{b^{a+2}\Gamma(a+2)} x^{a+2-1} \exp[-x/b]}_{=\operatorname{Gam}(a+2, b)} \mathrm{d}x\\
    &= a(a+1)b^2
\end{align*}
$$

従って，

$$
\begin{align*}
\operatorname{Var}(X)
    &= \mathbb E[X^2] - \mathbb E[X]^2\\
    &= a(a+1)b^2 - (ab)^2\\
    &= ab^2
\end{align*}
$$

<strong > &#9654;&nbsp; k次モーメントの導出</strong>

$k \in \mathbb Z_{++}$ について，k次モーメントは以下のように計算できます．

$$
\begin{align*}
\mathbb E[X^k]
    &= \int_0^\infty x^k \frac{1}{b^a\Gamma(a)}x^{a-1}\exp[-x/b]\,\mathrm{d}x\\[5pt]
    &= b^ka(a+1)\cdots(a+k-1)\underbrace{\int_0^\infty \frac{1}{b^{a+k}\Gamma(a+k)}x^{a+k-1}\exp[-x/b]}_{=\operatorname{Gam}(a+k, b)\text{のpdf}}\,\mathrm{d}x\\
    &= b^k \prod_{i=0}^{k-1}(a+i)
\end{align*}
$$



<div class="blog-custom-border">
::: {#thm- .custom_problem }
**: スケールパラメータ**
<br>

$X\sim\operatorname{Gam}(a, b)$ のとき，$c >0$ とする任意の定数について．$Y = cX$ としたとき

$$
Y \sim \operatorname{Gam}(a, bc)
$$

:::

</div>

::: {.callout-note collapse="false" icon=false}
## Proof

問題設定より

$$
\begin{gather}
Y = g(X) = c X\\
X = g^{-1}(Y) = \frac{1}{c} Y
\end{gather}
$$

$g(X)$ は狭義単調増加関数なので

$$
f_Y(y) = f_X(g^{-1}(y)) \frac{\mathrm{d}g^{-1}(y)}{\mathrm{d}y}
$$


従って，

$$
\begin{align*}
f_Y(y)
    &= \frac{1}{b^a\Gamma(a)}\left(\frac{y}{c}\right)^{a-1}\exp\left(-\frac{y}{bc}\right)\frac{1}{c}\\
    &= \frac{1}{(bc)^a\Gamma(a)}y^{a-1}\exp\left(-\frac{y}{bc}\right)
\end{align*}
$$

これは $\operatorname{Gam}(a-1, bc)$ の確率密度関数と一致します．

:::

## MGF

<div class="blog-custom-border">
::: {#thm- .custom_problem }
**: ガンマ分布の積率母関数と特性関数**
<br>

$\operatorname{Gam}(a, b)$ の積率母関数と特性関数は

$$
\begin{align*}
M_X(t) &= (1 - bt)^{-a}\\
\phi(t) &= (1 - bit)^{-a}
\end{align*}
$$

:::

</div>

::: {.callout-note collapse="false" icon=false}
## Proof

$$
\begin{align*}
M_X(t) &= \mathbb E[\exp(tX)]\\
    &= \int_0^\infty \exp(tx)\frac{1}{b^a\Gamma(a)} x^{a-1} \exp[-x/b] \mathrm{d}x\\
    &= \int_0^\infty\frac{1}{b^a\Gamma(a)} x^{a-1} \exp\left[-\frac{1-bt}{b}x\right] \mathrm{d}x\\
    &= (1-bt)^{-a}\int_0^\infty\frac{1}{(b/(1-bt))^a\Gamma(a)} x^{a-1} \exp\left[-\frac{1-bt}{b}x\right] \mathrm{d}x\\
    &= (1-bt)^{-a}
\end{align*}
$$

ただし，積率母関数が定義されるためには

$$
\frac{1-bt}{b}>0 \Rightarrow t< \frac{1}{b}
$$

が必要となることがわかります．特性関数は $\phi(t) = (1 - bit)^{-a}$

:::

## 他の確率分布との関係

<div class="blog-custom-border">
::: {#thm-gamma-and-chi-squared .custom_problem }
**: $\chi^2$分布との関係**
<br>

$m \in\mathbb Z_{++}$ とするとき，

$$
\operatorname{Gam}\big(x; a=m/2, b=2 \big) = \operatorname{\chi^2}(m)
$$

:::

</div>

::: {.callout-note collapse="false" icon=false}
## Proof

$\operatorname{Gam}(x; m/2, 2)$ の確率密度関数 $f(x)$ について

$$
\begin{align*}
f(x) = \frac{1}{2^{\frac{m}{2}}\Gamma(m/2)} x^{\frac{m}{2}-1} \exp[-x/2], \quad x > 0
\end{align*}
$$

と計算されます．これは $\operatorname{\chi^2}(m)$ の確率密度関数と一致します．

期待値，分散，MGFそれぞれを見てみると，$X\sim\operatorname{Gam}(x; m/2, 2)$ とすると，

$$
\begin{align*}
\mathbb E[X] &= 2\frac{m}{2} = m\\
\operatorname{Var}(X) &= 2^2\frac{m}{2} = 2m\\
M_X(t) &= [1 - 2t]^{-m/2} \quad (t < \frac{1}{2})
\end{align*}
$$

となり，$\operatorname{\chi^2}(m)$ の期待値，分散，MGFそれぞれと一致します．

:::