project:
  type: book
  output-dir: _book

book:
  title: "Statistics for Regression Monkeys"
  repo-url: https://github.com/RyoNakagami/statistics-for-regression-monkey
  site-url: https://ryonakagami.github.io/statistics-for-regression-monkey/
  google-analytics: 
    tracking-id: "G-QEFX7FVCDM"
  favicon: ./img/favicon.ico
  sharing: twitter
  sidebar:
      tools:
       - text: Blog Series
         icon: book
         menu:
         - text: Ryo's Tech Blog
           href: https://ryonakagami.github.io/
           aria-label: blog-general
         - text: statistics dojo
           href: https://ryonakagami.github.io/statistics_dojo/
           aria-label: blog-general
         - text: OhGoshGit!?!
           href: https://ohgoshgit.github.io/
           aria-label: blog-ogg
    
  repo-actions: [edit, issue]
  page-footer:
    center:
      - text: "© Copyright RyoNak"
      - text: "License"
        href: LICENSE
  chapters:
    - index.qmd
    - part: posts/statistics101/chapter_header.qmd
      chapters:
        - posts/statistics101/averages.qmd
        - posts/statistics101/correlation.qmd
        - posts/statistics101/infographics.qmd
        - posts/statistics101/random_variable.qmd
        - posts/statistics101/expectation.qmd
        - posts/statistics101/moment_generating_function.qmd
        - posts/statistics101/order_statistic.qmd
        - posts/statistics101/delta-method.qmd
    - part: posts/probability_distribution/chapter_header.qmd
      chapters: 
        - posts/probability_distribution/discrete_uniform_dist.qmd
        - posts/probability_distribution/binomial_dist.qmd
        - posts/probability_distribution/poisson_dist.qmd
        - posts/probability_distribution/geometric_dist.qmd
        - posts/probability_distribution/negative_binom.qmd
        - posts/probability_distribution/hypergeometric.qmd
        - posts/probability_distribution/continuous_uniform_dis.qmd
        - posts/probability_distribution/normal_dist.qmd
        - posts/probability_distribution/exponential_dist.qmd
        - posts/probability_distribution/gamma_dist.qmd
        - posts/probability_distribution/chi_squared_dist.qmd
    - part: posts/statistical_hypothesis_test_101/chapter_header.qmd
      chapters:
        - posts/statistical_hypothesis_test_101/fisher_exact_test.qmd
        - posts/statistical_hypothesis_test_101/ks_test.qmd
    - part: posts/statistical_hypothesis_test_201/chapter_header.qmd
      chapters:
        - posts/statistical_hypothesis_test_201/fisher_vs_neyman_pearson.qmd
    - part: posts/estimation/chapter_header.qmd
      chapters: 
        - posts/estimation/unbiased_estimator.qmd
        - posts/estimation/method-of-moments.qmd
        - posts/estimation/m-estimator.qmd
    - part: posts/bayesian_estimation/chapter_header.qmd
      chapters: 
        - posts/bayesian_estimation/bayesian_linear_regression.qmd
    - part: posts/ExplanatoryDataAnalysis/chapter_header.qmd
      chapters: 
        - posts/ExplanatoryDataAnalysis/gini_coefficient.qmd
    - part: posts/robust_statistics/chapter_header.qmd
    - part: posts/econometrics101/chapter_header.qmd
    - part: posts/prediction/chapter_header.qmd
      chapters: 
        - posts/prediction/bias_variance_in_prediction.qmd

  appendices: 
    - posts/mathematical_appendix/taylor_series.qmd
    - posts/mathematical_appendix/permutation_combination.qmd
    - posts/mathematical_appendix/complex_number.qmd
    - posts/mathematical_appendix/beta_function.qmd
    - posts/mathematical_appendix/gamma_function.qmd
    - posts/mathematical_appendix/jensen_inequality.qmd
    - posts/mathematical_appendix/Lhopitals_rule.qmd

format:
  html:
    include-in-header: 
      - include/setup_googletagmanager.html
      - include/custom_webfont.html
    include-in-body: include/setup_googletagmanager_body.html
    include-after-body: include/custom_section.html
    lang: ja_JP.UTF-8
    number-depth: 1
    jupyter: python3
    theme: 
      light: 
        - cosmo
        - include/custom.scss
        - include/light.scss
      dark: 
        - darkly
        - include/custom.scss
        - include/dark.scss
    code-copy: true
    code-fold: true
    code-overflow: wrap
    date-format: "iso"
    bibliography: references.bib
    biblatexoptions: bibstyle=jauthoryear,citestyle=numeric,natbib=true
    csl: reference.csl
    mainfont: "Noto Sans JP"
    monofont: monospace
