project:
  type: book
  output-dir: _book

book:
  title: "Statistics for Regression Monkeys"
  repo-url: https://github.com/RyoNakagami/statistics-for-regression-monkey
  site-url: https://ryonakagami.github.io/statistics-for-regression-monkey/
  google-analytics: 
    tracking-id: "G-QEFX7FVCDM"
  favicon: ./img/favicon.ico
  sharing: twitter
  repo-actions: [edit, issue]
  page-footer:
    center:
      - text: "© Copyright RyoNak"
      - text: "License"
        href: LICENSE
  chapters:
    - index.qmd
    - part: posts/statistics101/chapter_header.qmd
      chapters:
        - posts/statistics101/intro.qmd


format:
  typst:
    keep-typ: true
  html:
    include-in-header: 
      - include/setup_googletagmanager.html
      - include/custom_webfont.html
    include-in-body: include/setup_googletagmanager_body.html
    lang: ja_JP.UTF-8
    number-depth: 1
    theme: 
      light: cosmo
      dark: darkly
    code-copy: true
    code-fold: true
    code-overflow: wrap
    date-format: "iso"
    bibliography: references.bib
    biblatexoptions: bibstyle=jauthoryear,citestyle=numeric,natbib=true
    csl: reference.csl
    mainfont: "Noto Sans JP"
    monofont: monospace

  
