---
jupyter: python3
author: "Ryo Nakagtami"
date: "2024-07-20"
date-modified: last-modified
number_sections: false
code-fold: true
# when you run this file locally, do not forget to run poetry shell
---

# Welcome {.unnumbered}

このQuarto Bookは以下のシリーズと連動して運用されています:

|Blog Series|内容|
|:---:|:---|
|[Ryo's Tech Blog](https://ryonakagami.github.io/)|日々の徒然日記，Linuxまわりや開発お作法を主に取り扱う|
|[OhGoshGit!?!](https://ohgoshgit.github.io/)|Git trouble-shooting note|
|[statistics dojo](https://ryonakagami.github.io/statistics_dojo/)|統計学基礎問題練習ノート, Rを主に扱う|

### What is it about?

データ分析を学ぶ及び実践するにあたって５つの観点があると考えています：

1. 統計手法そのものの理解と，その背後にある数学を用いた理論の理解
2. 実際のデータに対して統計手法を用いた分析を実行するためのプログラミングスキル
3. データの前処理，環境構築，ソースコードのテストや管理，実装した推定量のデプロイなどのエンジニアリングスキル
4. 基本的な統計学の考え方や発想（例：データ分析のお作法や結果の解釈方法など）
5. そもそも解くべきの問題の見つけ方とその問題を特にあたっての方法論

このQuarto Bookではチャプターごとに各事項にフォーカスしてノートをまとめています．

<strong > &#9654;&nbsp; 参考書</strong>

|タイトル|説明|Citation|
|---|---|---|
|現代数理統計学|統計学入門|@2020現代数理統計学|
|P値: その正しい理解と適用|統計的仮説検定におけるP値の解説入門書|@P値-spotlight|
|サンプルサイズの決め方|統計的仮説検定におけるサンプルサイズ計算方法の解説本|@永田サンプルサイズ|

<strong > &#9654;&nbsp; プログラミング言語</strong>

- 主にPython 3.11.8 + [poetry](https://python-poetry.org/) を用います
- ケースに応じて，Rを用いる場合もあります
- 分析コードは[Repository](https://github.com/RyoNakagami/statistics-for-regression-monkey)のqmdファイルがそのままソースコードとなっています

参考として以下のようにコードブロックと合わせて出力されます．

```{python}
#| code-fold: show
print("Hallo World")
```

### Contributions

- ノートに関してBUG/Typos/不正確な表記を見つけた場合，まず[GitHub Issues](https://github.com/RyoNakagami/statistics-for-regression-monkey/issues/new)でIssue Raiseしていただけると助かります
- 各ノートの末尾に `utteranc.es` を用いたコメント欄があります．こちらはGitHub Discussionsと接続されておりますので，各ノートに関してはこちらも適宜ご利用ください

修正の必要性の判断は[RyoNak](https://github.com/RyoNakagami)が最終的には判断しますが，広く議論できたら幸いです
