name: Question
description: Ask a question about the project
title: "[QUESTION] "
labels: [question]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        **Question**
        A clear and concise question about the project.

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots related to your question here.
      placeholder: Add additional context here