---
title: "標本調査法"
author: "Ryo Nakagami"
date: "2024-10-12"
date-modified: last-modified
number_sections: false
code-fold: true
comments:
    utterances:
         repo: RyoNakagami/statistics-for-regression-monkey
         label: discussion
---

<strong > &#9654;&nbsp; 標本調査の目的</strong>

標本調査の目的は，母集団全体ではなく，その一部である標本を調べることで，母集団の特性値（平均や分散など）を推定することにあります．


<strong > &#9654;&nbsp; 標本調査と単位</strong>

とある母集団について統計的分析を行うとき，分析対象が集団である以上，その集団はその構成要素から成り立っていると考えるのが
普通ですが，その単位は以下のようなレベル別に考えることができます：

- 統計単位
- 観察単位(a unit of observation)
- 抽出単位

<div class="blog-custom-border">
<strong>Def: 統計単位</strong> <br>

調査で得られるデータに基づいて計算された各統計の単位のことを*統計単位*と呼ぶ．

個人を観察単位とするデータから，世帯別収入を計算し，その世帯別収入のヒストグラムという統計を作成した場合，世帯が*統計単位*となる．

</div>

農業センサスにおいては多くの項目の統計単位は農家または世帯ですが，調査内容によっては個人であったり，市区帳であったりします．
このように統計単位は１つの調査に固有のものではなく，調査で得られる各統計に固有なものとなります．

<div class="blog-custom-border">
<strong>Def: 観察単位</strong> <br>

調査法における*観察単位*はデータが収集される単位のことを指す．一方，Datasetにおける*観察単位*は基本的にはDatsetのindexの単位のことを指す．

</div>

調査法における観察単位とDatasetにおける観察単位が異なる例として，日本全国の小学校の校長を対象に郵送法で調査を実施したとき，前者の単位は小学校の校長となりますが，調査の質問内容が学校生徒個人に関する場合，その調査の結果得られたデータセットは日本の小学校に在籍している生徒個人となる可能性があります．

<div class="blog-custom-border">
<strong>Def: 抽出単位</strong> <br>

標本抽出の際に利用する単位のこと．国勢調査速報値の場合，調査員の受け持つ調査区域のこと．

</div>

抽出単位は調査毎に一意に定まるものではないことに注意が必要です．例として，2024年10月1日に日本に所在している世帯を母集団として，そこから1000世帯を標本抽出をするケースを考えます．このとき，全国の世帯に対して乱数を振り1000世帯を抽出することを考えた場合，抽出単位は世帯となりますが，

1. 市区町村を世帯人数規模に応じてサンプリング
2. 市区町村内をいくつかの調査区域に分けてサンプリング
3. 調査区域内部で世帯をサンプリング

という処理順番でサンプリングした場合，最終的に得られる観察単位は世帯となりますが，抽出単位は (市区町村，調査区，世帯) となります．
